#! /bin/sh
#
# $Id$
#
# This file outputs a list of pings and traceroutes for a server list to the
# screen.
#
# Adrian Chadd <adrian@psinet.net.au>
# Updated 22 March - Server cleanups
# Updated 10 April - Cleaned up servers and moved hostname, set email to routing@
#


# Uncomment and change this reflect your real hostname, then run
#HOSTNAME="server.somewhere.com.au"



# Lets firstly define how many servers to ping/traceroute
HOSTCOUNT="13"

# Now lets define each server.
HOST1="spin.nsw.au.austnet.org"
HOST2="webmaster.ca.us.austnet.org"
HOST3="yoyo.vic.au.austnet.org"
HOST4="iinet.wa.au.austnet.org"
HOST5="kas.vic.au.austnet.org"
HOST6="netspace.vic.au.austnet.org"
HOST7="bohica.tx.us.austnet.org"
HOST8="pacific.nsw.au.austnet.org"
HOST9="pacific.sg.austnet.org"
HOST10="tornado.no.eu.austnet.org"
HOST11="catcha.sg.austnet.org"
HOST12="starhub.sg.austnet.org"
HOST13="mediacorp.sg.austnet.org"

# Now lets set the packet count for the ping.
PINGCOUNT="50"

# Now lets set the location of the ping, traceroute and mail binaries


# Check the system we are on :)
if [ "`uname`" = "Linux" ]; then
  PING="/bin/ping"
  TRACEROUTE="/usr/bin/traceroute"
  MAIL="/bin/mail"
  REALHOST="`hostname -f`"
else
  # Assume BSD (eg FreeBSD)
  PING="/sbin/ping"
  TRACEROUTE="/usr/sbin/traceroute"
  MAIL="/usr/bin/mail"
  REALHOST="`hostname`"
fi

# Now lets set who we are mailing this to if you want a copy
EMAIL="routing@austnet.org"

# Ok - grab a temp file name
TEMPFILE="/tmp/austrace.temp"

rm -f $TEMPFILE 1> /dev/null 2> /dev/null # Lets be quiet about this :)



# ********************************************************************************************************************
#
# DO NOT MODFY ANYTHING UNDER THIS! 
#
# Ok, the checks.

if [ -x "$PING" ]; then
true
else
  echo "$PING does not exist or is not an executable binary!"
  exit
fi

if [ -x "$TRACEROUTE" ]; then
true
else
  echo "$TRACEROUTE does not exist or is not an executable binary!"
  exit
fi

if [ -x "$MAIL" ]; then
true
else
  echo "$MAIL does not exist or is not an executable binary!"
  exit
fi

if [ "$HOSTNAME" = "" ]; then
  echo "Please put your hostname in $HOSTNAME"
  exit
fi


# Now lets do the traceroute / ping bit.
COUNT="0"

# Main loop
while [ "$COUNT" != "$HOSTCOUNT" ]; do
  # First update the counter.
  COUNT="`expr $COUNT + 1`"

  # Next say what we're doing.
  eval TARGETHOST=\$HOST${COUNT}

  if [ "$TARGETHOST" = "" ]; then
    echo "Error : host #$COUNT has no valid HOST line in the script."
  else
    echo "Target host #$COUNT = $TARGETHOST"
    echo
     
    # Next - ping
    $PING -c $PINGCOUNT -q $TARGETHOST
  
    echo
    
    # Next step - traceroute
    $TRACEROUTE $TARGETHOST

  fi
  
  echo
  echo "--------"
  echo

done > $TEMPFILE 1>> $TEMPFILE 2>> $TEMPFILE


echo >> $TEMPFILE
echo >> $TEMPFILE
echo "Done." >> $TEMPFILE

# Now mail it. :)
cat $TEMPFILE | $MAIL -s "AUSTnet server pings / traceroutes from host $HOSTNAME ($REALHOST)" $EMAIL

# Now tidy up.
rm -f $TEMPFILE 1> /dev/null 2> /dev/null
